### ISSUE TITLE
The hot key [Ctrl]+[Shift]+[ESC] to stop recording in Sikuli-Slides is already in use for starting the Taskmanager

### ISSUE THREAD

**Issue by DMS2013** [sikuli/sikuli-slides#13]
When using the Sikuli-Slides recorder, [Ctrl]+[Shift]+2 would start and [Ctrl]+[Shift]+[ESC] would stop the recording.
For Windows 7 unfortunately the hot key  [Ctrl]+[Shift]+[ESC] will open the askmanager - so the recording kann not be stoped.

**Comment by zied1920** [comment]
I am facing the same issue and on windows 7 it's not possible to change keyboard short cuts, so when pressing  [Ctrl]+[Shift]+[ESC] the task manager is opened, this exception is generated :

Exception in thread "main" java.lang.NullPointerException
        at org.sikuli.recorder.Utils.stream2file(Utils.java:16)
        at org.sikuli.recorder.pptx.PPTXGenerator.createSkeletonDir(PPTXGenerator.java:164)
        at org.sikuli.recorder.pptx.PPTXGenerator.generate(PPTXGenerator.java:153)
        at org.sikuli.slides.apps.RecorderMain.main(RecorderMain.java:55)
        at org.sikuli.slides.apps.Main.main(Main.java:34)

And the slides are not saved.

**Comment by doubleshow** [comment]
![windows_7_x64](https://cloud.githubusercontent.com/assets/129562/3885328/bb008ffc-21bf-11e4-8a5d-b0590953aa06.png)
