### ISSUE TITLE
Running recorded slides fails to be executed by Sikuli slides app

### ISSUE THREAD

**Issue by malamunisamy** [sikuli/sikuli-slides#28]
Running recorded slides fails to be executed by Sikuli slides app. i have office 2010 in the system. it is looking for .rels and recorder doesn't create .rels file. i can open the created powerpoint fine in the powerpoint app.

java.io.FileNotFoundException: C:\Users\MMUNIS~1\AppData\Local\Temp\139518482611
2-0\helloworld1_rels.rels (The system cannot find the path specified)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at org.sikuli.slides.api.io.PPTXBundle.doUnZipFile(PPTXBundle.java:126)
        at org.sikuli.slides.api.io.PPTXBundle.<init>(PPTXBundle.java:61)
        at org.sikuli.slides.api.io.PPTXBundle.createFrom(PPTXBundle.java:48)
        at org.sikuli.slides.api.io.PPTXSlidesReader.read(PPTXSlidesReader.java:
26)
        at org.sikuli.slides.api.io.PPTXSlidesReader.read(PPTXSlidesReader.java:
56)
        at org.sikuli.slides.api.Slides.execute(Slides.java:61)
        at org.sikuli.slides.apps.ExecuteMain.execute(ExecuteMain.java:184)
        at org.sikuli.slides.apps.ExecuteMain.main(ExecuteMain.java:196)
        at org.sikuli.slides.apps.Main.main(Main.java:30)
File is not a valid pptx: C:\work\TestAutomationResources\helloworld1.pptx
Execution failed because java.io.IOException

**Comment by doubleshow** [comment]
The recorder only supported the 1.3 syntax. We will fix this in the upcoming 1.5 release.

**Comment by doubleshow** [comment]
Fixed
